compile_rust_module:
	cargo build --release
	mv target/release/libplayground_bot.so ../playground_bot.so

compile_rust_module_debug:
	cargo build
	mv target/debug/libplayground_bot.so ../playground_bot.so
